Updating csi plugin to support multi-arch builds
openshift/velero-plugin-for-csi pull request #2
Opened 2021-10-01 20:46 UTC by jaidevmane

Updated csi plugin to use the new konveyor/builder image to support multi-arch builds

2021-10-01 23:57 UTC, sseago reviewed
Same question here as I had on the openshift-velero-plugins one -- is the goal just to swap out the builder image, or do we want to use konveyor/builder as the *running* container image as well, which is what this PR does?

2021-10-04 13:28 UTC, dymurray requested changes
Please change only the builder image

2021-10-12 13:24 UTC, dymurray commented on Dockerfile.ubi
> +FROM quay.io/konveyor/builder
This should still be using `registry.access.redhat.com/ubi8-minimal`

2021-11-08 20:13 UTC, jmontleon commented
I'll be creating a PR shortly to address this and enable multiarch builds.

2021-11-08 20:13 UTC, closed without merging