OADP-1714 Upgrade golang.org/x/net to 0.7.0.
openshift/velero-plugin-for-csi pull request #65
Opened 2023-08-01 18:42 UTC by mrnold

2023-08-01 18:47 UTC, kaovilai requested changes
Please run `go mod tidy -compat=1.17` to remove entries from go.sum

2023-08-02 18:00 UTC, kaovilai approved these changes

2023-08-09 15:31 UTC, sseago commented
/lgtm

2023-08-09 15:31 UTC, sseago approved these changes

2023-08-09 15:32 UTC, merged